notifications:
  email: false

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    # FIXME: Currently i686 builds segfault (see issue #1))
    #- sudo: required
    #  services:
    #    - docker
    #  env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
    #       PRE_CMD=linux32

install:
  - pip install appveyor-artifacts
  - docker pull $DOCKER_IMAGE

script:
  - docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/build-wheels.sh
  - ls wheelhouse/

after_success:
  - appveyor-artifacts -c $(git rev-parse HEAD) -o jbaiter -n python-rust-fst download

deploy:
  provider: releases
  api_key:
    secure: 0MY7OzVqfPyEdynSZR2ke8VBEjMyAh6MHlXh9jlfdROgaoZ/TUNPlmlDtV+Dd/ZG/nIjcakoIWaFA3/Ta8ekYievoi/vtvdrecHem/O/9zmLglWKJwD3hukUw3w1/YngquzYqlKJrX9pYX3io3hFTUzxDx/5DXYiuRA7q8cvgmztAnDKtEqbRRMVc24Q54mbDmF000sELgumjAaCH3Ronu9f5zXIhrLHDp/gHAlH3LQ19/FNn7rNvx+ZfpLlHYN0RFunXuG7OcDsQMWv/TEUy+rjTV16z5N2xPmonFij37/w5bMgBjPPHTafky24avqoZvGaRDoCkQCU3STrl+pK/ljcnq7Et9Q4p1RPod0ypkh43FANUWsszB5AmTabDxINjFe7UTSsLnzOk7kDXmGU55ZQe87+x1l/GFm6CdZUrL4zkxzN5vA4COe9CGYC6EXieQaOADa62B9PmsbrZuaEUBVOWfSJuMXrTiIKjhB5gmqAuGNsRea8sIAdd9M4mMthLm0rLFrRIH/+W7jANRN7xiL1jchXkMLMn/Fse8jusxXfMF0DYFUYOXfro+ILGw6kCyLkgK5xhArKYahlUqVrHCSQA3PDG3G7F21HtYXhV0ZFnyrwiXZTOpKshMW7TLGYcnhbHbXuyHW4JpoFcFRuHmCZODBtQrfF/KbEAZ06P+8=
  file_glob: true
  file: ${HOME}/build/${TRAVIS_REPO_SLUG}/wheelhouse/rust_fst*.whl
  on:
    tags: true
